openapi: '3.0.2'
info:
  title: Inventory
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /inventory:
    get:
      tags:
        - pizzatype
      summary: Checks the inventory if the pizza type is in stock
      description: Checks the inventory if pizza type is in stock
      operationId: checkInventory
      parameters:
        - name: pizzaType
          schema:
            $ref: '#/components/schemas/PizzaType'
          in: query
          required: true
      responses:
        '200':
          description: Pizza type inventory successfully checked
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryResult'
    put:
      tags:
        - pizzatype
      summary: Updates the inventory for the given pizza type
      description: Updates the inventory for the given pizza type with the given stock count
      operationId: updateInventory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pizzaType:
                  $ref: '#/components/schemas/PizzaType'
                  example: pepperoni
                stockCount:
                  type: integer
                  format: int32
                  example: 5
        required: true
      responses:
        '200':
          description: Pizza type successfully updated
components:
  schemas:
    PizzaType:
      type: string
      enum:
        - pepperoni
        - margherita
        - hawaiian
        - hot pepper
    InventoryResult:
      type: object
      properties:
        pizzaType:
          $ref: '#/components/schemas/PizzaType'
        stockCount:
          type: integer
          format: int32
