@app_url=http://localhost:5064
@dapr_url= {{DAPR_HTTP_ENDPOINT}}
@workflow_id={{$guid}}
@currentDate={{$datetime iso8601}}

### 
### Start the workflow from the web api
###
POST {{app_url}}/workflow/orderReceived
Content-Type: application/json

{
    "OrderId": "{{workflow_id}}",
    "OrderDate": "{{currentDate}}",
    "Customer" : {
        "Name": "Leonardo",
        "Email": "leonardo@tmnt.shell"
    },
    "OrderItems": [
        {
            "PizzaType": "Pepperoni",
            "Quantity": 2
        },
        {
            "PizzaType": "Margherita",
            "Quantity": 1
        }
    ]
}

###
### Start the PizzaWorkflow
###
// @name wfrequest
POST {{dapr_url}}/v1.0-beta1/workflows/dapr/PizzaOrderWorkflow/start?instanceID={{workflow_id}}
dapr-api-token: {{DAPR_API_TOKEN}}
Content-Type: application/json

{
    "OrderId": "{{workflow_id}}",
    "OrderDate": "{{currentDate}}",
    "Customer" : {
        "Name": "Leonardo",
        "Email": "leonardo@tmnt.shell"
    },
    "OrderItems": [
        {
            "PizzaType": "Pepperoni",
            "Quantity": 2
        },
        {
            "PizzaType": "Margherita",
            "Quantity": 1
        }
    ]
}

### Get the status of the workflow
@wfresponse={{wfrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-beta1/workflows/dapr/{{wfresponse}}
dapr-api-token: {{DAPR_API_TOKEN}}

###
### Raise an event
### 
@event_name=order-prepared
POST {{dapr_url}}/v1.0-beta1/workflows/dapr/{{wfresponse}}/raiseEvent/{{event_name}}
dapr-api-token: {{DAPR_API_TOKEN}}
Content-Type: application/text

true