@dapr_url=http://localhost:3500
@workflow_id={{$guid}}
@currentDate={{$datetime iso8601}}

###
### Start the PizzaWorkflow
###
// @name wfrequest
POST {{dapr_url}}/v1.0-beta1/workflows/dapr/PizzaOrderWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

{
    "OrderId": "{{workflow_id}}",
    "OrderDate": "{{currentDate}}",
    "Customer" : {
        "Name": "Leonardo",
        "Email": "leonardo@tnm.shell"
    },
    "PizzasRequested": [
        {
            "PizzaType": "Pepperoni",
            "Quantity": 2
        }
    ]
}

### Get the status of the workflow
@wfresponse={{wfrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-beta1/workflows/dapr/{{wfresponse}}
