@app_url=http://localhost:5064
@dapr_url=http://localhost:3500
@workflow_id={{$guid}}
@currentDate={{$datetime iso8601}}

## Restock inventory
POST {{app_url}}/api/inventory/Restock



###
### Start the PizzaWorkflow
###
// @name wfrequest
POST {{dapr_url}}/v1.0-beta1/workflows/dapr/PizzaOrderWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

{

}

### Get the status of the workflow
@wfresponse={{wfrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-beta1/workflows/dapr/{{wfresponse}}
