name: Build and Publish .NET 8 Services

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 8.0.x
          - name: Restore PizzaOrderService dependencies
            run: dotnet restore back-end/PizzaOrderService/PizzaOrderService.csproj
          - name: Build PizzaOrderService service
            run: dotnet build back-end/PizzaOrderService/PizzaOrderService.csproj --no-restore


          - name: Restore KitchenService dependencies
            run: dotnet restore back-end/KitchenService/KitchenService.csproj
          - name: Build KitchenService service
            run: dotnet build back-end/KitchenService/KitchenService.csproj --no-restore
          - name: Publish KitchenService service
            run: dotnet publish back-end/KitchenService/KitchenService.csproj --output ./publish
          - name: Deploy to Azure Web App
            uses: azure/webapps-deploy@v2
            with:
              app-name: catalyst-kitchen-wa
              publish-profile: ${{ secrets.AZURE_WEBAPP_KITCHEN_PUBLISH_PROFILE }}
              package: ./publish
